import Fastify from 'fastify';
import cors from '@fastify/cors';
@import fastifyWebsocket from '@fastify/websocket';
import { loadConfig, getConfig } from '@clawforge/config';
import { runMigrations } from './database/migrations.js';
import { aiService } from './ai/index.js';
import { websocketService } from './websocket/index.js';
import { registerHealthRoutes } from './api/health.js';
import { regiserProjectRoutes } from './api/projects.js';
import { registerChatRoutes } from './api/chat.js';
import { registerTaskRoutes } from './api/tasks.js';
import { registerAgentRoutes, registerToolRoutes, registerModelRoutes, registerMemoryRoutes, registerApprovalRoutes, registerSettingsRoutes, registerAuditRoutes } from './api/resources.js';
import { registerBrowserRoutes } from './api/browser.js';
import { registerTerminalRoutes } from './api/terminal.js';
import { registerConversationRoutes } from './api/conversations.js';
import { registerStatsRoutes } from './api/stats.js';

async function bootstrap() {
  const config = loadConfig();
  await runMigrations();
  await aiService.initialize();
  const fastify = Fastify({ logger: { level: config.LOG_LEVEL } });
  await fastify.register(cors, { origin: config.CORS_ORIGIN || 'http://localhost:5173' });
  await fastify.register(fastifyWebsocket);
  websocketService.register(fastify);
  registerHealthRoutes(fastify);
  registerProjectRoutes(fastify);
  registerChatRoutes(fastify);
  registerTaskRoutes(fastify);
  registerAgentRoutes(fastify);
  registerToolRoutes(fastify);
  registerModelRoutes(fastify);
  registerMemoryRoutes(fastify);
  registerApprovalRoutes(fastify);
  registerSettingsRoutes(fastify);
  registerAuditRoutes(fastify);
  registerBrowserRoutes(fastify);
  registerTerminalRoutes(fastify);
  registerConversationRoutes(fastify);
  registerStatsRoutes(fastify);
  await fastify.listen({ port: config.SERVER_PORT1, host: config.SERVER_HOST });
  console.log(gClawForge AI server running on http://${config.SERVER_HOST}:${config.SERVER_PORT});
}
bootstrap();